### ISSUE TITLE
Sometimes captions doesn’t show until deleting instauto.save file

### ISSUE THREAD

**Issue by ItsFlorkast** [stanvanrooy/instauto#128] opened 2020-12-11 12:36 UTC
**Describe the bug**
Hello, 
I’m using instauto to post to instagram in different periods, sometimes it provides an empty caption for no reason. I tried things but it does not work at all. However, I finally solved this by removing instauto.save file and guess what? It works, it is strange.

**To Reproduce**
Keep the script running with a timer and after a certain time maybe it will appear ( sorry for bad explanation)

**Expected behavior**
I expect it to post the image with the caption not image only 😂

**Debug output**
Nothing at all

**Comment by LordArma** [comment] 2020-12-11 13:42
Because of this I never use instauto.save. You can also change your accounts password in period of times and then re-create your instauto.save file.

**Comment by stanvanrooy** [comment] 2020-12-11 15:13
Does this issue consistently happen until removing the save file?

**Comment by LordArma** [comment] 2020-12-11 15:14
> Does this issue consistently happen until removing the save file?

Yes.

**Comment by Anteeiiku** [comment] 2020-12-11 15:27
> Does this issue consistently happen until removing the save file?

Yes, also try to run the script more than two times

**Comment by stanvanrooy** [comment] 2020-12-11 17:04
Okay, thanks for the report.

I did a bit of digging and I'm suspecting this has something to do with some sort of session identifier being shared among multiple session for a long (longer then expected) period  of time.

Instagram notices that, and blocks some actions.

I'll be able to look at it more deeply after the weekend. 

Until then, my advise is to not use the save option if it is older then 1 hour.

**Comment by Anteeiiku** [comment] 2020-12-11 17:31
> Okay, thanks for the report.
> 
> I did a bit of digging and I'm suspecting this has something to do with some sort of session identifier being shared among multiple session for a long (longer then expected) period of time.
> 
> Instagram notices that, and blocks some actions.
> 
> I'll be able to look at it more deeply after the weekend.
> 
> Until then, my advise is to not use the save option if it is older then 1 hour.

Thanks and keep going 👏🏻.

**Comment by stanvanrooy** [comment] 2020-12-16 16:22
I've so far not been able to reproduce this. If any of you could set the logging to debug and forward me the logs, that would be an enormous  help.

You can either post the logs here, or send them to stan@rooy.dev.

Thanks

**Comment by Anteeiiku** [comment] 2021-01-17 16:22
> If any of you could set the logging to debug and forward me the logs, that would be an

Hi, sorry for late reply. 
to reproduce the issue you can simply make the script running and make a timer like every half hour you'll post picture and I guess after one hour it post with no caption or it will not post .

**Comment by ItsFlorkast** [comment] 2021-01-19 06:45
Hello @stanvanrooy, I have sent you an email which includes log file.
Thanks

**Comment by ItsFlorkast** [comment] 2021-01-20 21:17
Hello,
I'm still facing the issue, I tried my best to fix it but I couldn't. to reproduce the problem, just leave the save file for couple hours and you could try to upload a post with a caption, it will automatically post with caption =  'null' that's what appears after I looped resp in the post example. Also, I tried to update caption after this happened just as a temporary solution. However, it will give you an error ```    raise BadResponse("Received a non-200 response from Instagram")
instauto.api.exceptions.BadResponse: Received a non-200 response from Instagram```

I'll leave this issue open maybe someone will have a solution.

**Comment by stanvanrooy** [comment] 2021-01-20 21:23
> Hello @stanvanrooy, I have sent you an email which includes log file.
> Thanks

Thanks. I'll take a look at it asap.

**Comment by ItsFlorkast** [comment] 2021-01-22 21:35
Hi, any updates?

**Comment by ItsFlorkast** [comment] 2021-01-25 11:49
Hi ,
If you are unable to produce this issue please let me know.

**Comment by ItsFlorkast** [comment] 2021-01-31 22:40
Update: I tried another package which seems has the same issue. I read some people who talked about this issue and it seems Instagram for somehow know you are bot not a real person and blocks some features. If you could update session file **maybe** this issue will fixed. I'm not sure but I saw something like that in insauto package.

**Comment by stanvanrooy** [comment] 2021-02-01 12:02
Yes, that is what I already suspected. Usually when Instagram blocks an action, it returns with a pretty descriptive error message, that describes why exactly the decision to block the request was taken.

I couldn't find that in the logs, so I'm not sure what exact parameter is causing the blocking. Instauto already refreshes session parameters when a session is loaded from a save file, see https://github.com/stanvanrooy/instauto/blob/master/instauto/api/client.py#L159

**Comment by stanvanrooy** [comment] 2021-02-01 12:02
But no, I haven't been able to reproduce this consistently.

**Comment by ItsFlorkast** [comment] 2021-02-01 19:22
> Instauto already refreshes session parameters when a session is loaded from a save file, see https://github.com/stanvanrooy/instauto/blob/master/instauto/api/client.py#L159
Hello,
do you mean that the session id will be updated when the session loaded from a save file? and the save file will be updated ?

**Comment by ItsFlorkast** [comment] 2021-02-01 20:47
here something weird ;-;
the debug shows that instauto sent request to post **with** a caption
``` ******************** START REQUEST ********************
METHOD: POST
URL: https://i.instagram.com/api/v1/media/configure/
DATA: {'ig_sig_key_version': '4', 'signed_body': 'SIGNATURE.{"suggested_venue_position": -1, "multi_sharing": "-1", "caption": ".test", "size": [1080, 1080], "upload_id": "1612210878", "timezone_offset": "-28800", "scene_capture_type": "", "media_folder": "Pictures", "source_type": 4, "edits": {"crop_original_size": [1080, 1080], "crop_center": [0.0, 0.0], "crop_zoom": 1.0}, "extra": {"source_width": 1080, "source_height": 1080}, "device": {"manufacturer": "samsung", "model": "beyond1", "android_version": "29", "android_release": "10"}, "device_id": "android-43cd4ad49148be39"}'}
HEADERS: {'x-cm-bandwidth-kbps': '-1.000', 'x-cm-latency': '-1.000', 'x-ads-opt-out': '0', 'x-ig-app-locale': 'nl_NL', 'x-ig-app-startup-country': 'NL', 'x-ig-device-locale': 'nl_NL', 'x-ig-mapped-locale': 'nl_NL', 'x-ig-connection-speed': '3583kbps', 'x-ig-bandwidth-speed-kbps': '1193.879', 'x-ig-bandwidth-totalbytes-b': '0', 'x-ig-bandwidth-totaltime-ms': '0', 'x-ig-www-claim': '0', 'x-ig-device-id': 'a12eb2d8-43cd-4ad4-9148-be3922a64450', 'x-ig-android-id': 'android-43cd4ad49148be39', 'x-ig-connection-type': 'WIFI', 'x-ig-capabilities': '3brTvw8=', 'x-ig-app-id': '567067343352427', 'user-agent': 'Instagram 148.0.0.33.121 Android (29/10; 560dpi; 1440x2891; samsung; SM-973F; SM-973F; exynos9820; nl_NL; 227298996)', 'accept-language': 'nl_NL, en_US', 'x-mid': 'YBhcMAABAAGBuLgJMIt5LvSBwZXw', 'ig-u-rur': 'FTW', 'accept-encoding': 'gzip', 'x-fb-http-engine': 'Liger', 'authorization': 'Bearer IGT:2:eyJkc191c2VyX2lkIjoiMTU2NTI0MzI2NjMiLCJzZXNzaW9uaWQiOiIxNTY1MjQzMjY2MyUzQVVybkhuUDQ5bHNKWDd6JTNBOCIsInNob3VsZF91c2VfaGVhZGVyX292ZXJfY29va2llcyI6ZmFsc2V9', 'connection': 'close', 'x-pigeon-session-id': 'd9beb803-8571-43e3-b09a-96076b829e27', 'x-pigeon-rawclienttime': '1612209352.098', 'x-bloks-version-id': '5da07fc1b20eb4c7d1b2e6146ee5f197072cbbd193d2d1eb3bb4e825d3c39e28', 'x-bloks-is-layout-rtl': 'False', 'host': 'i.instagram.com', 'retry_context': '{"num_reupload": 0, "num_step_auto_retry": 0, "num_step_manual_retry": 0}', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
RESPONSE: b'{"media":{"taken_at":1612209352,"pk":2499715683760638703,"id":"2499715683760638703_15652432663","device_timestamp":1612210878,"media_type":1,"code":"CKwxiuaBorvpgm7H0zFtf_6Do_EL43ldZl-3LY0","client_cache_key":"MjQ5OTcxNTY4Mzc2MDYzODcwMw==.2","filter_type":0,"user":{"pk":15652432663,"username":"my_username","full_name":"ssss","is_private":true,"profile_pic_url":"https://instagram.flwo2-1.fna.fbcdn.net/v/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=instagram.flwo2-1.fna.fbcdn.net\\u0026_nc_ohc=tV0P-ansAXgAX_-3zkL\\u0026oh=e24046ecdeba4ae710a3c500b2667aee\\u0026oe=6040428F\\u0026ig_cache_key=YW5vbnltb3VzX3Byb2ZpbGVfcGlj.2","has_anonymous_profile_picture":true,"can_boost_post":false,"can_see_organic_insights":false,"show_insights_terms":false,"reel_auto_archive":"unset","is_unpublished":false,"allowed_commenter_type":"any","account_badges":[]},"can_viewer_reshare":true,"caption_is_edited":false,"comment_likes_enabled":false,"comment_threading_enabled":false,"has_more_comments":false,"max_num_visible_preview_comments":2,"preview_comments":[],"can_view_more_preview_comments":false,"comment_count":0,"hide_view_all_comment_entrypoint":false,"image_versions2":{"candidates":[{"width":1080,"height":1080,"url":"https://scontent-amt2-1.cdninstagram.com/v/t51.2885-15/e35/144473852_158675265868441_3010047029963786497_n.jpg?_nc_ht=scontent-amt2-1.cdninstagram.com\\u0026_nc_cat=101\\u0026_nc_ohc=bnjydfBkQ4QAX9UnnwB\\u0026se=8\\u0026tp=1\\u0026oh=032bb9ceee4a3e300cc14da64a9edf0f\\u0026oe=60407B17\\u0026ig_cache_key=MjQ5OTcxNTY4Mzc2MDYzODcwMw%3D%3D.2","scans_profile":"e35","estimated_scans_sizes":[29467,58935,88402,117870,147337,177836,215285,239756,265208]},{"width":480,"height":480,"url":"https://scontent-amt2-1.cdninstagram.com/v/t51.2885-15/e35/s480x480/144473852_158675265868441_3010047029963786497_n.jpg?_nc_ht=scontent-amt2-1.cdninstagram.com\\u0026_nc_cat=101\\u0026_nc_ohc=bnjydfBkQ4QAX9UnnwB\\u0026tp=1\\u0026oh=8409e125c4ec97adf8f88202e1cb18cc\\u0026oe=60424617\\u0026ig_cache_key=MjQ5OTcxNTY4Mzc2MDYzODcwMw%3D%3D.2","scans_profile":"e35","estimated_scans_sizes":[8010,16021,24031,32042,40052,49998,645732,72095,72095]}]},"original_width":1080,"original_height":1080,"photo_of_you":false,"can_see_insights_as_brand":false,"caption":null,"fb_user_tags":{"in":[]},"can_viewer_save":true,"organic_tracking_token":"eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjYzMjA4MDU3OWVkNjRmMzhhMDYxODA4ODEzNDk0ZjUzMjQ5OTcxNTY4Mzc2MDYzODcwMyIsInNlcnZlcl90b2tlbiI6IjE2MTIyMDkzNTU3OTB8MjQ5OTcxNTY4Mzc2MDYzODcwM3wxNTY1MjQzMjY2M3xkNTE0Y2VmMzY1OWFmNGYyOGZmOWZiMDUyYzQzNTI4NDllNmM4MjcwYzlkMTU3MTkwYjI2ODE0YWNiZmRmODEzIn0sInNpZ25hdHVyZSI6IiJ9","sharing_friction_info":{"should_have_sharing_friction":false,"bloks_app_url":null},"is_in_profile_grid":false,"profile_grid_control_enabled":false,"deleted_reason":0,"integrity_review_decision":"pending"},"upload_id":"1612210878","status":"ok"}'
******************** END REQUEST ********************
```
However, when I print resp parameter, it gives me that caption is **null**

``` b'{"media":{"taken_at":1612209352,"pk":2499715683760638703,"id":"2499715683760638703_15652432663","device_timestamp":1612210878,"m'
b'edia_type":1,"code":"CKwxiuaBorvpgm7H0zFtf_6Do_EL43ldZl-3LY0","client_cache_key":"MjQ5OTcxNTY4Mzc2MDYzODcwMw==.2","filter_type":'
b'0,"user":{"pk":15652432663,"username":"my_username","full_name":"ssss","is_private":true,"profile_pic_url":"https://instagram.flwo2-1.'
b'fna.fbcdn.net/v/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=instagram.flwo2-1.fna.fbcdn.net\\u0026_nc_o'
b'hc=tV0P-ansAXgAX_-3zkL\\u0026oh=e24046ecdeba4ae710a3c500b2667aee\\u0026oe=6040428F\\u0026ig_cache_key=YW5vbnltb3VzX3Byb2ZpbGVfcGlj.'
b'2","has_anonymous_profile_picture":true,"can_boost_post":false,"can_see_organic_insights":false,"show_insights_terms":false,"ree'
b'l_auto_archive":"unset","is_unpublished":false,"allowed_commenter_type":"any","account_badges":[]},"can_viewer_reshare":true,"ca'
b'ption_is_edited":false,"comment_likes_enabled":false,"comment_threading_enabled":false,"has_more_comments":false,"max_num_visibl'
b'e_preview_comments":2,"preview_comments":[],"can_view_more_preview_comments":false,"comment_count":0,"hide_view_all_comment_entr'
b'ypoint":false,"image_versions2":{"candidates":[{"width":1080,"height":1080,"url":"https://scontent-amt2-1.cdninstagram.com/v/t51'
b'.2885-15/e35/144473852_158675265868441_3010047029963786497_n.jpg?_nc_ht=scontent-amt2-1.cdninstagram.com\\u0026_nc_cat=101\\u0026_'
b'nc_ohc=bnjydfBkQ4QAX9UnnwB\\u0026se=8\\u0026tp=1\\u0026oh=032bb9ceee4a3e300cc14da64a9edf0f\\u0026oe=60407B17\\u0026ig_cache_key=MjQ5O'
b'TcxNTY4Mzc2MDYzODcwMw%3D%3D.2","scans_profile":"e35","estimated_scans_sizes":[29467,58935,88402,117870,147337,177836,215285,2397'
b'56,265208]},{"width":480,"height":480,"url":"https://scontent-amt2-1.cdninstagram.com/v/t51.2885-15/e35/s480x480/144473852_15867'
b'5265868441_3010047029963786497_n.jpg?_nc_ht=scontent-amt2-1.cdninstagram.com\\u0026_nc_cat=101\\u0026_nc_ohc=bnjydfBkQ4QAX9UnnwB\\u'
b'0026tp=1\\u0026oh=8409e125c4ec97adf8f88202e1cb18cc\\u0026oe=60424617\\u0026ig_cache_key=MjQ5OTcxNTY4Mzc2MDYzODcwMw%3D%3D.2","scans_'
b'profile":"e35","estimated_scans_sizes":[8010,16021,24031,32042,40052,49998,645732,72095,72095]}]},"original_width":1080,"origina'
b'l_height":1080,"photo_of_you":false,"can_see_insights_as_brand":false,"caption":null,"fb_user_tags":{"in":[]},"can_viewer_save":'
b'true,"organic_tracking_token":"eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6IjYzMjA4MDU3OWVkN'
b'jRmMzhhMDYxODA4ODEzNDk0ZjUzMjQ5OTcxNTY4Mzc2MDYzODcwMyIsInNlcnZlcl90b2tlbiI6IjE2MTIyMDkzNTU3OTB8MjQ5OTcxNTY4Mzc2MDYzODcwM3wxNTY1M'
b'jQzMjY2M3xkNTE0Y2VmMzY1OWFmNGYyOGZmOWZiMDUyYzQzNTI4NDllNmM4MjcwYzlkMTU3MTkwYjI2ODE0YWNiZmRmODEzIn0sInNpZ25hdHVyZSI6IiJ9","sharin'
b'g_friction_info":{"should_have_sharing_friction":false,"bloks_app_url":null},"is_in_profile_grid":false,"profile_grid_control_en'
b'abled":false,"deleted_reason":0,"integrity_review_decision":"pending"},"upload_id":"1612210878","status":"ok"}'```

so yes you are right instagram does not give an error about caption which it is weird ;-;

**Comment by stanvanrooy** [comment] 2021-02-07 22:29
@ItsFlorkast the above logging, contains your Bearer token. I'd suggest changing passwords, I'm pretty sure that revokes all authorization tokens.

I'll do some testing and experimenting tonight. I'll keep you updated.

**Comment by stanvanrooy** [comment] 2021-02-08 12:47
I've merged something into master that could potentially fix this. Not 100% sure. Maybe. It's worth a try.

**Comment by ItsFlorkast** [comment] 2021-02-08 18:02
I’ll give it a shot tonight and send you feedback on whether the issue fixed or not

**Comment by ItsFlorkast** [comment] 2021-02-09 11:36
Well, I tried it and I got the same issue after 6 hours. And a block from instagram. Not sure what causing the block since I just do it normal as before.

**Comment by stanvanrooy** [comment] 2021-02-12 10:53
Hmm, okay.

One last thing you could try is:
1. Check if the caption is correctly set in the response returned by `post_post`
2. Use `post_update_caption` to set the caption again, if not.

**Comment by ItsFlorkast** [comment] 2021-02-13 08:41
when the issue showed up I got `"caption":null` returned by `post_post`
And when I tried to update caption I got this error. Yes, the media id is correct. However, I couldn't update the caption So I tried to delete save file and guess what. It works. the caption has been updated with the same information before deleting save file.
```Traceback (most recent call last):
  File "C:\Users\king4\Desktop\my_project\test.py", line 21, in <module>
    client.post_update_caption(caption)
  File "C:\Users\king4\AppData\Roaming\Python\Python37\site-packages\instauto\api\actions\post.py", line 58, in post_update_caption
    return self._post_act(obj)
  File "C:\Users\king4\AppData\Roaming\Python\Python37\site-packages\instauto\api\actions\post.py", line 38, in _post_act
    return self._request(endpoint, Method.POST, data=obj.fill(self).to_dict(), signed=True)
  File "C:\Users\king4\AppData\Roaming\Python\Python37\site-packages\instauto\api\actions\request.py", line 233, in _request
    self._check_response_for_errors(resp)
  File "C:\Users\king4\AppData\Roaming\Python\Python37\site-packages\instauto\api\actions\request.py", line 269, in _check_response_for_errors
    raise BadResponse("Something unexpected happened. Please check the IG app.")
instauto.api.exceptions.BadResponse: Something unexpected happened. Please check the IG app.```

**Comment by hmdz105** [comment] 2021-02-19 14:01
I am facing the same issue. I have an app that runs all the time and uploads images to Instagram every 15 minutes. After about 1 and a half hours of being logged in and running, the images uploaded appear with "null" captions.

To my surprise, after null caption image upload,  the response from Instagram is:

Full response is: <Response [200]>
Success:  True

I can make the app log-out and log-in every 1.5 hours, but I have read that Instagram marks accounts with multiple logins logouts as bots and blocks them!

**Comment by ItsFlorkast** [comment] 2021-03-02 13:49
Hello,
Any updates?

**Closed** 2024-06-07 22:21 UTC
Labels: Type: Bug, ON_HOLD, Status: Ig block
